---

- name: Dob dev » Development Environment Setup
  include_role:
    name: zoidy_dobber_dev
    tasks_from: dev-dob
    apply:
      tags:
        - dev-dob
  tags: dev-dob
  # This task only runs if user sets the path to the dev dir.
  when: zoidy_dob_dev_dob_working_tree != ''

