---

- name: Hamster Dob/Nark Development Environment Setup
  include_role:
    name: zoidy_dob-dev
    tasks_from: dev-dob
    apply:
      tags:
        - dev-dob
  tags: dev-dob
  # This task only runs if user sets the path to the dev dir.
  when:
    (zoidy_dob_dev_nark_and_dob_dir != '') or (zoidy_dob_dev_support_libs_dir != '')

