---

# NOTE: To set up the virtual environment, we need to source the
# virtualenvwrapper script for each call -- and for the `source`
# command to work, we need to run Bash. E.g., you'll see this a lot:
#
#     args:
#       # Run Bash so `source` works.
#       executable: /bin/bash

# ***

- set_fact:
    VENV_PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

# ***

- name: Dob dev: Install Virtualenv and wrapper
  command: "pip3 install --user --upgrade {{ item }}"
  loop:
    - virtualenv
    - virtualenvwrapper

# ***

- name: Dob dev: Install github-release tool
  # Specify "-u"/update to always update projects previously got.
  command: "go get -u {{ item }}"
  environment:
    PATH: "{{ VENV_PATH }}"
    GOPATH: "{{ ansible_env.HOME }}/.gopath"
  loop:
    - github.com/aktau/github-release

# ***

- name: Dob dev: Remove existing virtual environment
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    rmvirtualenv {{ zoidy_dob_dev_venv_name }}
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

- name: Dob dev: Create virtual environment
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    mkvirtualenv \
      -a {{ zoidy_dob_dev_nark_and_dob_dir }}/dob \
      --python={{ zoidy_dob_dev_python_bin }} \
      {{ zoidy_dob_dev_venv_name }}
  args:
    chdir: "{{ zoidy_dob_dev_nark_and_dob_dir }}/dob"
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

# NOTE: In following tasks, we use `cd` in shell command, rather than using
#       Ansible `chdir`, because workon changes the working directory.

# ***

# Editable projects installed via: pip3 install -U -e .

- name: Dob dev: Pip-install editable projects
  loop: "{{ zoidy_dob_dev_libs_editable }}"
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cd {{ item }} && \
    pip3 install -U -e .
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

# Editable projects with their own make install task: make develop.

- name: Dob dev: Make-install editable projects
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cd {{ item }} && \
    make develop
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"
  loop:
    - "{{ zoidy_dob_dev_support_libs_dir }}/config-decorator"
    - "{{ zoidy_dob_dev_support_libs_dir }}/human-friendly_pedantic-timedelta"
    - "{{ zoidy_dob_dev_support_libs_dir }}/pep440-version-compare-cli"
    - "{{ zoidy_dob_dev_nark_and_dob_dir }}/nark"
    - "{{ zoidy_dob_dev_nark_and_dob_dir }}/dob-bright"
    - "{{ zoidy_dob_dev_nark_and_dob_dir }}/dob-prompt"
    - "{{ zoidy_dob_dev_nark_and_dob_dir }}/dob-viewer"
    - "{{ zoidy_dob_dev_nark_and_dob_dir }}/dob"

# ***

- name: Wire dob plugins for hacking
  loop: "{{ zoidy_dob_dev_dobs_editable }}"
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cd {{ item }} && \
    pip3 install -U -e .
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ VENV_PATH }}"

# ***

- name: Install dob plugins
  loop: "{{ zoidy_dob_dev_plugin_paths }}"
  shell: >
    source {{ zoidy_dob_dev_user_local_bin_dir }}/virtualenvwrapper.sh && \
    workon {{ zoidy_dob_dev_venv_name }} && \
    cd {{ item }} && \
    pip3 install -U -e . \
    {{ item | basename }} install
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.virtualenvs/{{ zoidy_dob_dev_venv_name }}/bin:{{ VENV_PATH }}"

